- name: Verificar o billing diário da AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Verificar billing
      aws_billing:
        start_time: "{{ lookup('pipe', 'date -u -d \"-1 day\" \"+%Y-%m-%dT00:00:00Z\"') }}"
        end_time: "{{ lookup('pipe', 'date -u \"+%Y-%m-%dT00:00:00Z\"') }}"
        granularity: DAILY
      register: billing

    - name: Exibir resultados
      debug:
        var: billing

